apiVersion: v1
kind: Service
metadata:
  name: m1ga-service-example
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    # goes to your desigred pods
    app: m1ga-deployment
